project_id = "xgvaibxxiwfraklfbwey"

[functions.hello-public]
verify_jwt = false

[functions.sync-diagnostics-v2]
verify_jwt = false

[functions.sync-diagnostics]
verify_jwt = false

[functions.scrape-posts]
verify_jwt = false

[functions.fix-posts]
verify_jwt = false

[functions.trigger-sync]
verify_jwt = false